// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, non_constant_identifier_names
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// await Firebase.initializeApp(
//     options = DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrUTdlGJbZlMXC6adMvGS1MGYHAz8mGq8',
    appId: '1:554730337685:web:1497c29fc200f54e44329c',
    messagingSenderId: '554730337685',
    projectId: 'videochat-app-e4d32',
    authDomain: 'videochat-app-e4d32.firebaseapp.com',
    storageBucket: 'videochat-app-e4d32.appspot.com',
    measurementId: 'G-1GLGDPYGW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrzEpCLgfoDUE3M5suQGojFLuQOKhVWcQ',
    appId: '1:554730337685:android:bf091683d8609b5644329c',
    messagingSenderId: '554730337685',
    projectId: 'videochat-app-e4d32',
    storageBucket: 'videochat-app-e4d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp9zetl_M49V00_1pOAch_x95XccfxAmE',
    appId: '1:554730337685:ios:897eeb7655f6611544329c',
    messagingSenderId: '554730337685',
    projectId: 'videochat-app-e4d32',
    storageBucket: 'videochat-app-e4d32.appspot.com',
    iosClientId:
        '554730337685-5713j6cng7e45n5rhhf27qku6s83gce7.apps.googleusercontent.com',
    iosBundleId: 'com.example.videochatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp9zetl_M49V00_1pOAch_x95XccfxAmE',
    appId: '1:554730337685:ios:dda2ccdca20a9a0b44329c',
    messagingSenderId: '554730337685',
    projectId: 'videochat-app-e4d32',
    storageBucket: 'videochat-app-e4d32.appspot.com',
    iosClientId:
        '554730337685-r9n53p35101se69bun4i6euv67qk8nmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.videochatApp.RunnerTests',
  );
}
